# Data Cleaning & Feature Engineering

## Objective
Prepare the banking customer churn dataset for SQL analysis, machine learning, and business intelligence.

## Tasks
- Validate data types and missing values
- Remove duplicate records if necessary
- Handle categorical variables
- Create meaningful customer segments
- Create features that may improve churn analysis
- Validate the processed dataset
- Export the cleaned dataset for downstream analysis

In [4]:
import pandas as pd
import numpy as np

# Load the raw dataset
df = pd.read_csv(
    r"C:\Users\amish\OneDrive\Desktop\portfolio\fintech-customer-churn-retention\data\raw\Bank Customer Churn Prediction.csv"
)

# Check the dataset
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (10000, 12)

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Check missing values
print("Missing values by column:")
print(df.isnull().sum())

# Check duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

Missing values by column:
customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

Number of duplicate rows: 0

In [6]:
# Check data types
print("Data types:")
print(df.dtypes)

# Check unique values for categorical/binary columns
print("\nCountry values:")
print(df["country"].unique())

print("\nGender values:")
print(df["gender"].unique())

print("\nCredit card values:")
print(df["credit_card"].unique())

print("\nActive member values:")
print(df["active_member"].unique())

print("\nChurn values:")
print(df["churn"].unique())

Data types:
customer_id           int64
credit_score          int64
country              object
gender               object
age                   int64
tenure                int64
balance             float64
products_number       int64
credit_card           int64
active_member         int64
estimated_salary    float64
churn                 int64
dtype: object

Country values:
['France' 'Spain' 'Germany']

Gender values:
['Female' 'Male']

Credit card values:
[1 0]

Active member values:
[1 0]

Churn values:
[1 0]

In [7]:
# Check ranges of numerical variables
print("Credit score:", df["credit_score"].min(), "to", df["credit_score"].max())
print("Age:", df["age"].min(), "to", df["age"].max())
print("Tenure:", df["tenure"].min(), "to", df["tenure"].max())
print("Balance:", df["balance"].min(), "to", df["balance"].max())
print("Products:", df["products_number"].min(), "to", df["products_number"].max())
print("Estimated salary:", df["estimated_salary"].min(), "to", df["estimated_salary"].max())

# Check binary variables
print("\nCredit card:", sorted(df["credit_card"].unique()))
print("Active member:", sorted(df["active_member"].unique()))
print("Churn:", sorted(df["churn"].unique()))

Credit score: 350 to 850
Age: 18 to 92
Tenure: 0 to 10
Balance: 0.0 to 250898.09
Products: 1 to 4
Estimated salary: 11.58 to 199992.48

Credit card: [np.int64(0), np.int64(1)]
Active member: [np.int64(0), np.int64(1)]
Churn: [np.int64(0), np.int64(1)]

In [8]:
# Create a working copy of the raw dataset
clean_df = df.copy()

# Confirm the copy
print("Original dataset shape:", df.shape)
print("Clean dataset shape:", clean_df.shape)

Original dataset shape: (10000, 12)
Clean dataset shape: (10000, 12)

In [9]:
# Create age groups
clean_df["age_group"] = pd.cut(
    clean_df["age"],
    bins=[17, 25, 35, 45, 55, np.inf],
    labels=["18-25", "26-35", "36-45", "46-55", "56+"]
)

# Check the result
print(clean_df["age_group"].value_counts().sort_index())

age_group
18-25     611
26-35    3542
36-45    3736
46-55    1311
56+       800
Name: count, dtype: int64

In [10]:
# Create balance groups
clean_df["balance_group"] = pd.cut(
    clean_df["balance"],
    bins=[-1, 50000, 100000, 150000, 200000, np.inf],
    labels=["0-50K", "50K-100K", "100K-150K", "150K-200K", "200K+"]
)

# Check the result
print(clean_df["balance_group"].value_counts().sort_index())

balance_group
0-50K        3692
50K-100K     1509
100K-150K    3830
150K-200K     935
200K+          34
Name: count, dtype: int64

In [11]:
# Create credit score groups
clean_df["credit_score_group"] = pd.cut(
    clean_df["credit_score"],
    bins=[349, 579, 669, 739, 799, 850],
    labels=["Poor", "Fair", "Good", "Very Good", "Excellent"]
)

# Check the result
print(clean_df["credit_score_group"].value_counts().sort_index())

credit_score_group
Poor         2362
Fair         3331
Good         2428
Very Good    1224
Excellent     655
Name: count, dtype: int64

In [12]:
# Create estimated salary groups
clean_df["salary_group"] = pd.cut(
    clean_df["estimated_salary"],
    bins=[-1, 50000, 100000, 150000, np.inf],
    labels=["0-50K", "50K-100K", "100K-150K", "150K+"]
)

# Check the result
print(clean_df["salary_group"].value_counts().sort_index())

salary_group
0-50K        2453
50K-100K     2537
100K-150K    2555
150K+        2455
Name: count, dtype: int64

In [13]:
# Create customer activity segment
clean_df["activity_segment"] = np.where(
    clean_df["active_member"] == 1,
    "Active",
    "Inactive"
)

# Check the result
print(clean_df["activity_segment"].value_counts())

activity_segment
Active      5151
Inactive    4849
Name: count, dtype: int64

In [15]:
# Create product segment
clean_df["product_segment"] = pd.cut(
    clean_df["products_number"],
    bins=[0, 1, 2, 4],
    labels=["1 Product", "2 Products", "3-4 Products"]
)

# Check the result
print(clean_df["product_segment"].value_counts().sort_index())

product_segment
1 Product       5084
2 Products      4590
3-4 Products     326
Name: count, dtype: int64

In [16]:
# Check missing values in engineered features
engineered_features = [
    "age_group",
    "balance_group",
    "credit_score_group",
    "salary_group",
    "activity_segment",
    "product_segment"
]

print(clean_df[engineered_features].isnull().sum())

age_group             0
balance_group         0
credit_score_group    0
salary_group          0
activity_segment      0
product_segment       0
dtype: int64

In [17]:
# Final validation of the cleaned dataset

print("Original shape:", df.shape)
print("Cleaned shape:", clean_df.shape)

print("\nCleaned dataset columns:")
print(clean_df.columns.tolist())

print("\nMissing values:")
print(clean_df.isnull().sum().sum())

print("\nDuplicate rows:")
print(clean_df.duplicated().sum())

Original shape: (10000, 12)
Cleaned shape: (10000, 18)

Cleaned dataset columns:
['customer_id', 'credit_score', 'country', 'gender', 'age', 'tenure', 'balance', 'products_number', 'credit_card', 'active_member', 'estimated_salary', 'churn', 'age_group', 'balance_group', 'credit_score_group', 'salary_group', 'activity_segment', 'product_segment']

Missing values:
0

Duplicate rows:
0

In [18]:
# Final quality check for engineered features

for col in engineered_features:
    print(f"\n{col}:")
    print(clean_df[col].unique())

age_group:
['36-45', '46-55', '26-35', '18-25', '56+']
Categories (5, object): ['18-25' < '26-35' < '36-45' < '46-55' < '56+']

balance_group:
['0-50K', '50K-100K', '150K-200K', '100K-150K', '200K+']
Categories (5, object): ['0-50K' < '50K-100K' < '100K-150K' < '150K-200K' < '200K+']

credit_score_group:
['Fair', 'Poor', 'Good', 'Excellent', 'Very Good']
Categories (5, object): ['Poor' < 'Fair' < 'Good' < 'Very Good' < 'Excellent']

salary_group:
['100K-150K', '50K-100K', '0-50K', '150K+']
Categories (4, object): ['0-50K' < '50K-100K' < '100K-150K' < '150K+']

activity_segment:
['Active' 'Inactive']

product_segment:
['1 Product', '3-4 Products', '2 Products']
Categories (3, object): ['1 Product' < '2 Products' < '3-4 Products']

In [19]:
import os

# Create processed data folder
processed_path = r"C:\Users\amish\OneDrive\Desktop\portfolio\fintech-customer-churn-retention\data\processed"

os.makedirs(processed_path, exist_ok=True)

print("Processed data folder is ready.")

Processed data folder is ready.

In [20]:
# Export cleaned and feature-engineered dataset

output_file = os.path.join(
    processed_path,
    "bank_customer_churn_processed.csv"
)

clean_df.to_csv(output_file, index=False)

print("Processed dataset saved successfully!")
print(output_file)

Processed dataset saved successfully!
C:\Users\amish\OneDrive\Desktop\portfolio\fintech-customer-churn-retention\data\processed\bank_customer_churn_processed.csv

In [21]:
# Verify the exported processed dataset

processed_df = pd.read_csv(output_file)

print("Processed dataset shape:", processed_df.shape)
print("\nMissing values:", processed_df.isnull().sum().sum())
print("Duplicate rows:", processed_df.duplicated().sum())

print("\nFirst 5 rows:")
display(processed_df.head())

Processed dataset shape: (10000, 18)

Missing values: 0
Duplicate rows: 0

First 5 rows:

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,age_group,balance_group,credit_score_group,salary_group,activity_segment,product_segment
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,36-45,0-50K,Fair,100K-150K,Active,1 Product
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,36-45,50K-100K,Fair,100K-150K,Active,1 Product
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,36-45,150K-200K,Poor,100K-150K,Inactive,3-4 Products
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,36-45,0-50K,Good,50K-100K,Inactive,2 Products
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,36-45,100K-150K,Excellent,50K-100K,Active,1 Product

## Conclusion

The banking customer churn dataset was successfully cleaned and prepared for downstream analysis.

### Data Quality
- 10,000 customer records were validated.
- No missing values were found.
- No duplicate records were identified.
- Data types and categorical values were validated.
- Numerical ranges were checked for potential invalid values.

### Feature Engineering
Six business-oriented features were created:
- `age_group`
- `balance_group`
- `credit_score_group`
- `salary_group`
- `activity_segment`
- `product_segment`

The processed dataset contains 18 columns and was exported to:

`data/processed/bank_customer_churn_processed.csv`

This processed dataset will be used for SQL business KPI analysis, machine learning, and Power BI dashboard development.